language: node_js
node_js: stable
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_9210b3126f4f_key -iv $encrypted_9210b3126f4f_iv
  -in deploy_rsa.enc -out deploy_rsa -d  
addons:
  ssh_known_hosts:
  - 101.132.172.137
install:
- npm install
script:
- npm run build
after_success:
- ssh  ./dist/* root@101.132.172.137:/usr/share/nginx/html/test-travis/
# - rsync -az --delete ./dist/* root@101.132.172.137:/usr/share/nginx/html/test-travis/
